import 'package:google_translator/isar_model.dart';
import 'package:isar/isar.dart';
import 'package:path_provider/path_provider.dart';

class IsarService {
  late Isar isar;

  Future<void> initializeIsar() async {
    final dir = await getApplicationDocumentsDirectory();
    isar = await Isar.open(
      [ProfileImageSchema], // Schema generated by Isar
      directory: dir.path,
    );
  }

  Future<void> insertProfileImage(ProfileImage profileImage) async {
    await isar.writeTxn(() async {
      await isar.profileImages
          .put(profileImage); // Insert the profile image record
    });
  }

  Future<void> closeIsar() async {
    await isar.close();
  }
}
